web:
  build: .
  volumes:
    - "./app:/src/app"
    - "./public:/src/public"
  ports:
    - "3030:3000"
  links:
    - db
  command: forever start app/bin/www

db:
  image: mysql:latest
  volumes:
    - ../db/survey:/var/lib/mysql
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: docker
    MYSQL_DATABASE: docker
    MYSQL_USER: docker
    MYSQL_PASSWORD: docker