web:
  build: .
  volumes:
    - "./app:/src/app"
    - "./public:/src/public"
  ports:
    - "3030:3000"
  links:
    - db
  command: nodemon -L app/bin/www
  environment:
    PORT: 3000
    SURVEY_PROVIDER: json
    SURVEY_SRC: /src/app/data/test_survey.json
    DB_PROVIDER: mysql
    DB_USER: docker
    DB_PASS: docker

db:
  image: mysql:latest
  volumes:
    - ../db/survey:/var/lib/mysql
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: docker
    MYSQL_DATABASE: docker
    MYSQL_USER: docker
    MYSQL_PASSWORD: docker