web:
  build: .
  volumes:
    - "./app:/src/app"
    - "./public:/src/public"
  ports:
    - "3001:3000"
  links:
    - db:db
  command: ./app/node_modules/nodemon/bin/nodemon.js --legacy-watch app/bin/www
  environment:
    PORT: 3000
    SURVEY_PROVIDER: csv
    SURVEY_SRC: /src/app/data/test_survey.csv
    DB_HOST: db
    DB_USER: docker
    DB_PASS: docker
    DB_DB: survey
    DB_PORT: 3306

db:
  image: mysql:latest
  volumes:
    - ../db/survey:/var/lib/mysql
    - ./app/database/migrations/init_schema.sql:/tmp/init_schema.sql
    - ./app/database/migrations/init.sh:/tmp/import.sh
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: docker
    MYSQL_DATABASE: survey
    MYSQL_USER: docker
    MYSQL_PASSWORD: docker